// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/23/2024, 2:10:35 AM
const configMerger = require("/Users/ctp/Documents/GitHub/blog-cristi/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/ctp/Documents/GitHub/blog-cristi/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ctp/Documents/GitHub/blog-cristi/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ctp/Documents/GitHub/blog-cristi/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ctp/Documents/GitHub/blog-cristi/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ctp/Documents/GitHub/blog-cristi/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ctp/Documents/GitHub/blog-cristi/plugins/**/*.{js,ts,mjs}","/Users/ctp/Documents/GitHub/blog-cristi/composables/**/*.{js,ts,mjs}","/Users/ctp/Documents/GitHub/blog-cristi/utils/**/*.{js,ts,mjs}","/Users/ctp/Documents/GitHub/blog-cristi/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ctp/Documents/GitHub/blog-cristi/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ctp/Documents/GitHub/blog-cristi/app.config.{js,ts,mjs}"] }));

module.exports = config
